[tool.black]
line-length = 84
include = 'trapper'
exclude = '''
(
  ^/(
    | .git
    | .github
    | .idea
    | .pytest_cache
    | .venv
    | examples
    | trapper.egg-info
    | venv
  )/
    | __pycache__
)
'''
